module dfrs {
	struct Result {
		boolean success;
		string content;
	};
	
	interface DFRS {
		Result transferReservation(in long passengerID, in string currentCity, in string otherCity);
  		string getBookedFlightCount(in string recordType);
  		Result editFlightRecord(in long recordID, in string fieldName, in string newValue);
  		Result bookFlight(in string firstName, in string lastName, in string address, 
							in string phone, in string destination, in string date, in string ticketClass);
		string getAllFlightInfo();
  	};
};