package dfrs;


/**
* dfrs/DFRSPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/workspace/CORBA_Assignment/src/dfrs.idl
* 2016年11月6日 星期日 下午10时16分49秒 EST
*/

public abstract class DFRSPOA extends org.omg.PortableServer.Servant
 implements dfrs.DFRSOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("transferReservation", new java.lang.Integer (0));
    _methods.put ("getBookedFlightCount", new java.lang.Integer (1));
    _methods.put ("editFlightRecord", new java.lang.Integer (2));
    _methods.put ("bookFlight", new java.lang.Integer (3));
    _methods.put ("getAllFlightInfo", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // dfrs/DFRS/transferReservation
       {
         int passengerID = in.read_long ();
         String currentCity = in.read_string ();
         String otherCity = in.read_string ();
         dfrs.Result $result = null;
         $result = this.transferReservation (passengerID, currentCity, otherCity);
         out = $rh.createReply();
         dfrs.ResultHelper.write (out, $result);
         break;
       }

       case 1:  // dfrs/DFRS/getBookedFlightCount
       {
         String recordType = in.read_string ();
         String $result = null;
         $result = this.getBookedFlightCount (recordType);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // dfrs/DFRS/editFlightRecord
       {
         int recordID = in.read_long ();
         String fieldName = in.read_string ();
         String newValue = in.read_string ();
         dfrs.Result $result = null;
         $result = this.editFlightRecord (recordID, fieldName, newValue);
         out = $rh.createReply();
         dfrs.ResultHelper.write (out, $result);
         break;
       }

       case 3:  // dfrs/DFRS/bookFlight
       {
         String firstName = in.read_string ();
         String lastName = in.read_string ();
         String address = in.read_string ();
         String phone = in.read_string ();
         String destination = in.read_string ();
         String date = in.read_string ();
         String ticketClass = in.read_string ();
         dfrs.Result $result = null;
         $result = this.bookFlight (firstName, lastName, address, phone, destination, date, ticketClass);
         out = $rh.createReply();
         dfrs.ResultHelper.write (out, $result);
         break;
       }

       case 4:  // dfrs/DFRS/getAllFlightInfo
       {
         String $result = null;
         $result = this.getAllFlightInfo ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:dfrs/DFRS:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public DFRS _this() 
  {
    return DFRSHelper.narrow(
    super._this_object());
  }

  public DFRS _this(org.omg.CORBA.ORB orb) 
  {
    return DFRSHelper.narrow(
    super._this_object(orb));
  }


} // class DFRSPOA
