package dfrs;


/**
* dfrs/DFRSHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/workspace/CORBA_Assignment/src/dfrs.idl
* 2016年11月6日 星期日 下午10时16分49秒 EST
*/

abstract public class DFRSHelper
{
  private static String  _id = "IDL:dfrs/DFRS:1.0";

  public static void insert (org.omg.CORBA.Any a, dfrs.DFRS that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static dfrs.DFRS extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (dfrs.DFRSHelper.id (), "DFRS");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static dfrs.DFRS read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_DFRSStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, dfrs.DFRS value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static dfrs.DFRS narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof dfrs.DFRS)
      return (dfrs.DFRS)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      dfrs._DFRSStub stub = new dfrs._DFRSStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static dfrs.DFRS unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof dfrs.DFRS)
      return (dfrs.DFRS)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      dfrs._DFRSStub stub = new dfrs._DFRSStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
